from pydantic import BaseModel, Field
from datetime import datetime
from typing import List, Dict, Any, Optional
import uuid


class RetrievedChunk(BaseModel):
    """
    Model representing a content chunk retrieved from the RAG pipeline.
    This is a nested model used within AgentResponse.

    Attributes:
        content: The actual content text
        similarity_score: Similarity score from retrieval (0-1)
        chunk_id: Unique identifier for the chunk
        metadata: Additional metadata about the source
        position: Position in the original document
    """
    content: str
    similarity_score: float = Field(ge=0.0, le=1.0)
    chunk_id: str
    metadata: Dict[str, Any]
    position: int


class AgentResponse(BaseModel):
    """
    Model representing the response generated by the AI agent.

    Attributes:
        response_text: The agent's response to the query (1-10000 characters)
        query_id: Reference to the original query
        retrieved_chunks: List of content chunks used (at least one when response is generated)
        confidence_score: Confidence level of the response (0-1)
        response_id: Unique identifier for the response (auto-generated)
        created_at: Timestamp when the response was created (auto-generated)
        sources: List of source references
        metadata: Additional response metadata
    """
    response_text: str = Field(..., min_length=1, max_length=10000)
    query_id: str
    retrieved_chunks: List[RetrievedChunk]
    confidence_score: float = Field(ge=0.0, le=1.0)
    response_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = Field(default_factory=datetime.utcnow)
    sources: Optional[List[str]] = []
    metadata: Optional[Dict[str, Any]] = {}

    class Config:
        # Allow extra fields in case additional parameters are added
        extra = "allow"
        # Enable ORM mode for potential database integration
        orm_mode = True

    def __init__(self, **data):
        super().__init__(**data)
        # Validate that retrieved_chunks has at least one chunk when response is generated
        if not data.get('retrieved_chunks') or len(data['retrieved_chunks']) == 0:
            # This is a relaxed validation since sometimes we might want to create responses without chunks
            # The validation can be more strict depending on the use case
            pass