"""
Model representing a numerical representation of content text generated by Cohere models.
"""
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional


@dataclass
class EmbeddingVector:
    """
    A numerical representation of content text generated by Cohere models,
    stored in Qdrant with associated metadata.
    """
    vector: List[float]
    chunk_id: str
    model_name: str
    embedding_id: Optional[str] = None
    created_at: Optional[datetime] = None

    def __post_init__(self):
        """Validate the embedding vector after initialization."""
        if not self.vector:
            raise ValueError("Vector cannot be empty")

        # Validate vector dimensions (typically 1024 for Cohere)
        if len(self.vector) == 0:
            raise ValueError("Vector must have consistent dimensions")

        if not self.chunk_id:
            raise ValueError("Chunk_id must reference an existing content chunk")

        if not self.model_name:
            raise ValueError("Model name must be from approved list")

        if self.created_at is None:
            self.created_at = datetime.now()

        if self.embedding_id is None:
            # Generate a unique embedding ID
            import uuid
            self.embedding_id = str(uuid.uuid4())