openapi: 3.0.0
info:
  title: RAG Agent API
  description: API for interacting with the RAG-enabled AI agent
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server
paths:
  /api/v1/agent/query:
    post:
      summary: Submit a query to the RAG agent
      description: Process a user query using the AI agent with book content context
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentQueryRequest'
      responses:
        '200':
          description: Successful response from the agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/agent/health:
    get:
      summary: Check the health status of the agent service
      description: Verify that the agent service is running and accessible
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
components:
  schemas:
    AgentQueryRequest:
      type: object
      required:
        - query_text
      properties:
        query_text:
          type: string
          description: The user's question or query text
          example: "What are the key concepts in neural networks?"
        context_text:
          type: string
          description: Optional selected text provided as context
          example: "Neural networks are computing systems inspired by the human brain..."
        query_type:
          type: string
          description: Type of query
          enum: [general, context-specific]
          default: general
    AgentResponse:
      type: object
      required:
        - response_text
        - query_id
        - retrieved_chunks
        - confidence_score
        - response_id
        - created_at
      properties:
        response_text:
          type: string
          description: The agent's response to the query
          example: "Neural networks are computing systems..."
        query_id:
          type: string
          description: Reference to the original query
          format: uuid
        retrieved_chunks:
          type: array
          items:
            $ref: '#/components/schemas/RetrievedChunk'
          description: List of content chunks used to generate the response
        confidence_score:
          type: number
          format: float
          description: Confidence level of the response (0-1)
          minimum: 0
          maximum: 1
          example: 0.85
        response_id:
          type: string
          description: Unique identifier for the response
          format: uuid
        created_at:
          type: string
          format: date-time
          description: Timestamp when the response was created
        sources:
          type: array
          items:
            type: string
          description: List of source references
        metadata:
          type: object
          description: Additional response metadata
    RetrievedChunk:
      type: object
      required:
        - content
        - similarity_score
        - chunk_id
        - metadata
        - position
      properties:
        content:
          type: string
          description: The actual content text
          example: "Artificial neural networks are computing systems..."
        similarity_score:
          type: number
          format: float
          description: Similarity score from retrieval (0-1)
          minimum: 0
          maximum: 1
          example: 0.92
        chunk_id:
          type: string
          description: Unique identifier for the chunk
          format: uuid
        metadata:
          type: object
          description: Additional metadata about the source
        position:
          type: integer
          description: Position in the original document
          example: 1
    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "AGENT_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "Failed to process query due to retrieval error"
        details:
          type: object
          description: Additional error details
    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          description: Health status of the service
          enum: [healthy, unhealthy]
          example: "healthy"
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the health check
        services:
          type: object
          description: Status of dependent services
          additionalProperties:
            type: object
            properties:
              status:
                type: string
                enum: [healthy, unhealthy]
              details:
                type: string
                description: Additional service details