openapi: 3.0.0
info:
  title: RAG Retrieval API
  description: API for semantic search and retrieval from embedded book content in Qdrant
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/v1/search:
    post:
      summary: Perform semantic search in embedded book content
      description: Retrieve relevant text chunks from Qdrant using similarity search against Cohere embeddings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The search query text
                  example: "What are the key concepts in AI?"
                top_k:
                  type: integer
                  default: 5
                  minimum: 1
                  maximum: 50
                  description: Number of results to return
                similarity_threshold:
                  type: number
                  format: float
                  default: 0.5
                  minimum: 0.0
                  maximum: 1.0
                  description: Minimum similarity score for inclusion
      responses:
        '200':
          description: Search completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  query_id:
                    type: string
                    description: Unique identifier for the query
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/RetrievedChunk'
                  total_results:
                    type: integer
                    description: Total number of results returned
                  query_time_ms:
                    type: number
                    format: float
                    description: Time taken to execute the query in milliseconds
                  search_params:
                    type: object
                    properties:
                      top_k:
                        type: integer
                        description: Number of results requested
                      similarity_threshold:
                        type: number
                        format: float
                        description: Minimum similarity threshold used
                  status:
                    type: string
                    enum: [success, partial, no_results]
                    description: Status of the query execution
        '400':
          description: Invalid query parameters
        '500':
          description: Server error during search

  /api/v1/validate:
    post:
      summary: Validate retrieval quality with test queries
      description: Run multiple test queries to validate retrieval accuracy and relevance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                test_queries:
                  type: array
                  items:
                    type: object
                    properties:
                      query_text:
                        type: string
                        description: The test query text
                      expected_chunks:
                        type: array
                        items:
                          type: string
                        description: Expected chunk IDs that should be returned
                      min_similarity:
                        type: number
                        format: float
                        default: 0.7
                        description: Minimum similarity score expected
                  description: Array of test queries with expected results
                validation_params:
                  type: object
                  properties:
                    accuracy_threshold:
                      type: number
                      format: float
                      default: 0.9
                      description: Minimum accuracy required for validation
                    top_k:
                      type: integer
                      default: 5
                      description: Number of results to check for each query
      responses:
        '200':
          description: Validation completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  validation_id:
                    type: string
                    description: Unique identifier for the validation run
                  total_tests:
                    type: integer
                    description: Total number of test queries executed
                  passed_tests:
                    type: integer
                    description: Number of tests that passed validation
                  failed_tests:
                    type: integer
                    description: Number of tests that failed validation
                  overall_accuracy:
                    type: number
                    format: float
                    description: Overall accuracy percentage
                  detailed_results:
                    type: array
                    items:
                      type: object
                      properties:
                        test_id:
                          type: string
                          description: Unique identifier for the test
                        query_text:
                          type: string
                          description: The test query text
                        actual_results:
                          type: array
                          items:
                            $ref: '#/components/schemas/RetrievedChunk'
                          description: Actual results returned
                        expected_results:
                          type: array
                          items:
                            type: string
                          description: Expected chunk IDs
                        passed:
                          type: boolean
                          description: Whether this test passed
                        accuracy:
                          type: number
                          format: float
                          description: Accuracy for this specific test
                  validation_status:
                    type: string
                    enum: [passed, failed, partial]
                    description: Overall validation status
        '400':
          description: Invalid validation parameters
        '500':
          description: Server error during validation

  /api/v1/health:
    get:
      summary: Check API health status
      description: Verify that the retrieval service is operational
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy, degraded, unavailable]
                    description: Overall health status
                  qdrant_connection:
                    type: string
                    enum: [connected, disconnected]
                    description: Qdrant database connection status
                  response_time_ms:
                    type: number
                    format: float
                    description: Response time in milliseconds

components:
  schemas:
    RetrievedChunk:
      type: object
      properties:
        content:
          type: string
          description: The actual text content of the retrieved chunk
        similarity_score:
          type: number
          format: float
          description: A numerical value representing the semantic relevance to the search query
        chunk_id:
          type: string
          description: Identifier for the source chunk in the original embedding database
        metadata:
          $ref: '#/components/schemas/MetadataPackage'
        position:
          type: integer
          description: Sequential position of the chunk within the source document
      required:
        - content
        - similarity_score
        - chunk_id
        - metadata

    MetadataPackage:
      type: object
      properties:
        url:
          type: string
          format: uri
          description: Source URL of the original document
        section:
          type: string
          description: Section or heading in the original document
        chunk_id:
          type: string
          description: Identifier for the specific chunk
        document_id:
          type: string
          description: Identifier for the source document
        document_title:
          type: string
          description: Title of the source document
        source_type:
          type: string
          description: Type of source document (e.g., "docusaurus-page")
      required:
        - url
        - chunk_id
        - document_id

    SearchQuery:
      type: object
      properties:
        query_text:
          type: string
          description: The input text for the semantic search
        top_k:
          type: integer
          default: 5
          description: Number of results to retrieve
        similarity_threshold:
          type: number
          format: float
          default: 0.5
          description: Minimum similarity score for inclusion
        query_id:
          type: string
          description: Unique identifier for the query
        created_at:
          type: string
          format: date-time
          description: Timestamp of query creation
      required:
        - query_text